PYTHON_VERSION = '3.5m'
BOOST_PYTHON_LIB_NAME = 'boost_python-py35' 
PYTHON_INCLUDE_PATH = '/usr/include/python' + PYTHON_VERSION

env = Environment(CPPPATH=[PYTHON_INCLUDE_PATH], CXXFLAGS='-std=c++11')
env['SHLIBPREFIX'] = ''
env.SharedLibrary('chance', ['chance.cpp'], LIBS=['python' + PYTHON_VERSION, BOOST_LIB_NAME])

